tasks:
  - name: Temporalite
    init: go install github.com/robholland/temporalite/cmd/temporalite@0e3dbdd81573719b55d487f1df06bc40ba522de6
    command: temporalite start --namespace default --ephemeral
  - name: Remote Codec Server
    env:
      ENCRYPTION_KEY_ID: test-key
    command: |
      echo Starting Remote Codec Server
      echo Endpoint: $(gp url 8234)
      echo Origin: $(gp url 8233)
      echo
      go run ./codecserver -origin $(gp url 8233)
  - name: Shell
    env:
      ENCRYPTION_KEY_ID: test-key
    init: |
      go install github.com/temporalio/tctl/cmd/tctl@v1.16.1
      go mod download

ports:
  - port: 7233 # temporal server
    onOpen: ignore
  - port: 8233 # temporal web
    onOpen: open-browser
  - port: 8234 # remote codec server
    onOpen: ignore
    visibility: public
    
